apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc04
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  storageClassName: slow

